### ISSUE TITLE
Readme needs update

### ISSUE THREAD

**Issue by Lauloque** [HoroTW/RazerBatteryTray#9]
Couple of issues I got:

1. I just installed this on KDE Neon as per the readme's insctruction, but it doesn't work when using the proposed command to execute the py script as we didn't go in the directory it is actually located.

2. I couldn't seem to be able to run the py script, I got the following error:

```python
$ ./razer_battery_tray.py
Traceback (most recent call last):
  File "/home/roikku/.local/lib/python3.10/site-packages/pystray/_appindicator.py", line 24, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roikku/Repositories/RazerBatteryTray/src/./razer_battery_tray.py", line 8, in <module>
    from rbt_manager import RazerBatteryTrayManager
  File "/home/roikku/Repositories/RazerBatteryTray/src/rbt_manager.py", line 9, in <module>
    import pystray
  File "/home/roikku/.local/lib/python3.10/site-packages/pystray/__init__.py", line 64, in <module>
    Icon = backend().Icon
  File "/home/roikku/.local/lib/python3.10/site-packages/pystray/__init__.py", line 56, in backend
    return candidate()
  File "/home/roikku/.local/lib/python3.10/site-packages/pystray/__init__.py", line 28, in appindicator
    from . import _appindicator as backend; return backend
  File "/home/roikku/.local/lib/python3.10/site-packages/pystray/_appindicator.py", line 27, in <module>
    gi.require_version('AyatanaAppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AyatanaAppIndicator3 not available
```

Following similar error reports on other python tray icon projects like [here](https://github.com/yktoo/indicator-docker/issues/5) and [there](https://github.com/techgaun/nepali-calendar-indicator/issues/5), I had to install the following to make it work:  
`sudo apt install gir1.2-appindicator3-0.1`

**Comment by HoroTW** [comment]
Thank you very much for your contribution, and I apologise for the delayed response.

I have added some information about the need for `AppIndicator` in the README.

As far as I can tell, this stems from Wayland not having a single tray icon solution (not sure if X11 really had one.. ^^'). I already had `AppIndicator` installed, probably as a dependency from another app.
